### ISSUE TITLE
Bug in xTerm

### ISSUE THREAD

**Issue by antonbrams** [dwb/atom-xterm#3]
ptyw.js@0.4.1 – The module '/Users/antonkluev/.atom/packages/xterm/node_modules/ptyw.js/build/Release/pty.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 49. This version of Node.js requires NODE_MODULE_VERSION 53. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or`npm install`)

**Comment by dwb** [comment]
Atom should have given you some UI to rebuild packages? Or trying uninstalling and reinstalling?

**Comment by dwb** [comment]
P.S. – sorry for getting back so late! Not sure what's happening to my email notifications.

**Comment by antonbrams** [comment]
no prob... i've rebuild it and it runs :)

**Comment by dwb** [comment]
👍
