### ISSUE TITLE
Support opening terminal in a dock

### ISSUE THREAD

**Issue by dcalhoun** [dwb/atom-xterm#7]
Would you be willing to support opening a terminal in a [dock](https://atom.io/docs/api/v1.20.0/Dock) rather than a pane? How difficult do you think adding that support would be?

**Comment by dwb** [comment]
I thought there were plenty of terminal plugins that already do this? I feel it rather complicates keyboard navigation – if terminals aren't in panes and tabs, you have to start assigning your own keyboard shortcuts specifically for focussing/blurring your terminal, and I'm not ultra keen on that.

**Comment by dcalhoun** [comment]
You are correct. There are other plugins that provide this functionality. If this is outside the scope of your project, that is fine.

**Comment by dwb** [comment]
Ideally this plugin would be a complete solution, catering for every reasonable workflow. But if I'm being honest with myself, only the stuff that fits in with how I use it every day is going to get the love necessary for proper maintenance! Sorry about that, but I don't want to ship something that will get neglected.
